### PR TITLE
Fixes an error in the OBB orientation calculation

### LINKED ISSUE #99: Probably a bug in OBBShape::getCentroid()
After modifying the orientation of an OBB goal in one of the examples, I started receiving the exception:
`Can't compute a path to a goal outside of the navigation mesh.  Bad NavMeshVelComponent!`

I believe there is a bug in calculating the centroid of the OBB shape.
The current implementation is:
`return _pivot + getXBasis() * (_size.x() * 0.5f) + getYBasis() * (_size.y() * 0.5f);`

while it should be:
`Vector2 centerPoint(_size.x() * 0.5f, _size.y() * 0.5f);`
`return _pivot + Vector2(getXBasis() * centerPoint, getYBasis() * centerPoint);`

### PR DESCRIPTION
**Pull request by curds01**
The documentation of getXBasis() and getYBasis() did *not* agree with what
was actually returned. This led to an incorrect result in computing the OBB
centroid.

1. This elaborates on the documentation and how the basis vectors should be used.
2. It also corrects usage in OBBShape::setDirections and OBBShape::getTargetPoint

Note to reviewer: some lines appear changed because whitespace has changed (tabs swapped for spaces -- sorry about that.)

Fixes #99

---
This change is [Reviewable](https://reviewable.io/reviews/mengecrowdsim/menge/100)

### CODE REVIEW

**Comment by MengeCrowdSim** [comment]
@alafi I think this should fix your issue. Wanna take a look?

**Comment by alafi** [comment]
The fix seems to be flipping the OBB (or the rendering is erroneous?).
As per the documentation for the OBB, a positive angle causes counter-clockwise rotation. This is not the case after applying the fix.

Check the images below from the `randomGoal` example.
Quote from the behavior file:
`<Goal type="OBB" id="1" x="-1" y="5" width="2" height="2" angle="10.0" weight="1.0" />`

image
image

File: src/Menge/MengeCore/Math/Geometry2D.h [hunk 1]
```diff
@@ -747,19 +747,97 @@ namespace Menge {
...
+
+      Conversely, the matrix `R_GW = R_WG^T = [Bx By]^T` re-expresses in the *geometry* frame a vector
+      that was previously expressed in the world frame.
+
+      In practice, for a position vector from the world origin to point Q expressed in the world frame,
+      r_WQ_W, we can calculate a position vector from the geometry frame's origin r_WG (the OBB's
+      pivot) and expressed in the geometry frame as:
+      `r_GQ = [(r_WQ - r_WG) * Bx, (r_WQ - r_WG) * By]^T` or
+      `r_GQ = R_GW * (r_WQ - r_WG)`.
+      Functionality that becomes:
```
Comment (curds01) [inline src/Menge/MengeCore/Math/Geometry2D.h]: "Functionally, that becomes:"

File: src/Menge/MengeCore/Math/Geometry2D.h [hunk 2]
```diff
@@ -747,19 +747,97 @@ namespace Menge {
...
+
+      ```
+      Vector2 r_WQ_W;
+      Vector2 Bx = getXBasis();
+      Vector2 By = getYBasis();
+      Vector2 r_GQ_W = r_WQ - pivot_;
```
Comment (curds01) [inline src/Menge/MengeCore/Math/Geometry2D.h]: This would be clearer if the definitions of `Bx` and `By` came *after* `r_GQ_W`. (Same for `getYBasis()`.)

**Comment by curds01** [comment]
Blast! I was so focused on making sure that the numbers were internally consistent, that I didn't look for that. Great catch. I'll address it and ping you again.

**Comment by MengeCrowdSim** [comment]
This is what *I* see. Did you pull the branch onto an older version of master?

capture

**Comment by MengeCrowdSim** [comment]
Ah...the difference is between release and debug. So, release looks right, debug looks wrong...

capture

File: src/Menge/MengeCore/Math/Geometry2D.h (hunk 1 above)
Comment (curds01) [reply src/Menge/MengeCore/Math/Geometry2D.h]: Done

**Comment by curds01** [comment]
Ok, I've updated the commit and I believe *this* fixes things.

(Also the release vs debug thing may *not* have been 100% accurate. There's a vague chance that VisualStudio didn't update everything it should've. However, *this* feels good.) 

Moral of the story: I *desperately* need to get unit testing into Menge. A HUGE glaring hole...

**Comment by alafi** [comment]
OK, this seems like fixed it.

However, I am still getting the following assertion failed every while and then:
`Assertion failed: det( right, preferred )>= SPAN_EPS, file ..\..\..\src\Menge\mengeCore\Agents\PrefVelocity.cpp, line 106`

Here are the parameter values for one of the incidents:
`right = {_x=-0.573575854 _y=0.819152474 }`
`preferred = {_x=1.00000000 _y=0.000000000 }`

The exception is thrown when calling `PrefVelocity::setSpan` in `OBBShape::setDirections` so it might be related to this issue. BTW it used to happen before and still happening  after the fix.

Thank you for the great work and your follow up.

**Comment by curds01** [comment]
Without looking to the code, I suspect I know the problem. The vector [1, 0] is *most likely* the default result when normalizing a zero vector. Obviously, in this case, that's a bad thing. I think I know where to look for that and I'll tackle it this evening. Once I look at it, I *may* include it in this PR, or I may PR it separately (the separate being a case of suspecting that there are mostly likely multiple instances of that across all the goals....)

**Comment by MengeCrowdSim** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[releaseNotes.txt, line 3 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/100#-LDyEVDOAyd_rhcnOObr:-LDyEVDOAyd_rhcnOObs:b-2maz4r) ([raw file](https://github.com/mengecrowdsim/menge/blob/55061712be1471618b0a2b86e3a50b16326543fc/releaseNotes.txt#L3)):*
> ```
> ----------------------------------------------------------------
> Release 0.9.3
> 	???? ??, 2018
> ```

FYI spaces instead of tabs

---

*[src/Menge/MengeCore/Math/Geometry2D.h, line 777 at r1](https://reviewable.io/reviews/mengecrowdsim/menge/100#-LDyEpB40nUCwQKw0j8D:-LDyEpB40nUCwQKw0j8E:bovjcg) ([raw file](https://github.com/mengecrowdsim/menge/blob/55061712be1471618b0a2b86e3a50b16326543fc/src/Menge/MengeCore/Math/Geometry2D.h#L777)):*
> ```objc
>       @brief    Returns the x-axis of the OBB's local frame expressed in the world frame.
> 
>       If we say that Bx = getXBasis() and By = getYBasis(), are *column* vectors, we can define the 2x2
> ```

BTW (Meta) Line too long

---


*Comments from [Reviewable](https://reviewable.io/reviews/mengecrowdsim/menge/100)*

**Comment by MengeCrowdSim** [comment]
:LGTM:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/mengecrowdsim/menge/100#-:-LDyOHKTBVjZi5DojRqT:bmxilld)*
